# Generated by Django 4.0.5 on 2022-06-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Título')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('imagen', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
                ('notas', models.TextField(null=True, verbose_name='Notas')),
            ],
        ),
    ]
