# Generated by Django 4.0.5 on 2022-07-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_rentakids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre del Cliente'),
        ),
    ]
